language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: Wp+stkuCnbBhLi96PZdzRO/lVYAwSYQvrirEYsj0oc9mEngqM1JO0iMRLcH4LXaGDEF7dFqOeSkSO3x/2zSBQPoj+HI9dCs/FYJJz0TlQGGL3ga49KswHRHL2sfduqAlqM5s1XoQb2M0hj2YlgdXh5TnVReBs/ohzhcSZ54NtEM=
  - secure: htIxAzXfqxPeudqXdevMWE+P1T2FgWL3ToTkeB9Ob/pYHy3aZtBcCN57l4sB6mIoQhUcSc2Rpwia43fBJPxVBSsRgACkq1RsiZ6y3K248A765Qs9v6nPOG3rfy5EUrdRwqIrgSlrK9pVahxydYnbBCLjOQu9R04CzUtoJVwJ3cE=
